ALTER TABLE view360
    ADD COLUMN IF NOT EXISTS title VARCHAR(255),
    ADD COLUMN IF NOT EXISTS order_index INT CHECK (order_index IS NULL OR order_index >= 0),
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

UPDATE view360
SET title = CONCAT('View360 #', view_id)
WHERE title IS NULL OR title = '';

ALTER TABLE view360
    ALTER COLUMN title SET NOT NULL;

ALTER TABLE view360_image
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_view360_deleted_at
    ON view360(deleted_at);

CREATE INDEX IF NOT EXISTS idx_view360_image_deleted_at
    ON view360_image(deleted_at);

