ALTER TABLE map
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE map
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE map
SET created_at = CURRENT_TIMESTAMP
WHERE created_at IS NULL;

UPDATE map
SET updated_at = CURRENT_TIMESTAMP
WHERE updated_at IS NULL;
