module.exports = {
  auth: require('./auth.controller'),
  user: require('./user.controller'),
  destinationCategory: require('./destinationCategory.controller'),
  tourCategory: require('./tourCategory.controller'),
  tour: require('./tour.controller'),
  travelDestination: require('./travelDestination.controller'),
  location: require('./location.controller'),
  view360: require('./view360.controller'),
  view360Image: require('./view360Image.controller'),
  map: require('./map.controller'),
  nearby: require('./nearby.controller'),
  navigation: require('./navigation.controller'),
  booking: require('./booking.controller'),
  bookingDetail: require('./bookingDetail.controller'),
  payment: require('./payment.controller'),
  coupon: require('./coupon.controller'),
  blog: require('./blog.controller'),
  blogLocation: require('./blogLocation.controller'),
  review: require('./review.controller'),
  statistics: require('./statistics.controller'),
  chat: require('./chat.controller'),
  suggestion: require('./suggestion.controller'),
};
