module.exports = {
  common: require('./common.validator'),
  auth: require('./auth.validator'),
  entity: require('./entity.validator'),
  user: require('./user.validator'),
  tour: require('./tour.validator'),
  location: require('./location.validator'),
  coupon: require('./coupon.validator'),
  payment: require('./payment.validator'),
  sepayWebhook: require('./sepayWebhook.validator'),
  map: require('./map.validator'),
  nearby: require('./nearby.validator'),
  mapFilter: require('./mapFilter.validator'),
  navigation: require('./navigation.validator'),
  view360: require('./view360.validator'),
  view360Image: require('./view360Image.validator'),
  review: require('./review.validator'),
  reviewPhoto: require('./reviewPhoto.validator'),
};
