module.exports = {
  common: require('./common.validator'),
  auth: require('./auth.validator'),
  entity: require('./entity.validator'),
  user: require('./user.validator'),
  tour: require('./tour.validator'),
  tourContentItem: require('./tourContentItem.validator'),
  location: require('./location.validator'),
  coupon: require('./coupon.validator'),
  payment: require('./payment.validator'),
  sepayWebhook: require('./sepayWebhook.validator'),
  zaloWebhook: require('./zaloWebhook.validator'),
  map: require('./map.validator'),
  nearby: require('./nearby.validator'),
  mapFilter: require('./mapFilter.validator'),
  navigation: require('./navigation.validator'),
  view360: require('./view360.validator'),
  view360Hotspot: require('./view360Hotspot.validator'),
  view360Image: require('./view360Image.validator'),
  review: require('./review.validator'),
  reviewPhoto: require('./reviewPhoto.validator'),
  blogComment: require('./blogComment.validator'),
  media: require('./media.validator'),
  refundRequest: require('./refundRequest.validator'),
  travelFeed: require('./travelFeed.validator'),
  travelStory: require('./travelStory.validator'),
  groupTrip: require('./groupTrip.validator'),
};
